### ISSUE TITLE
Not working when outside Wi-Fi

### ISSUE THREAD

**Issue by jensni-ch** [trupici/G-Watch-Wear#14]
Everything is working so far, we installed G-Watch App and configured Dexcom Share. We can see the graph on the watch face.
However, as soon as we go outside the house it's not working anymore. There is no more data sent to the watch.
As soon as we enter the house, the data is being transmitted.

Is there a requirement that the watch itselves has to have access to the internet, or is the G-Watch App only working over Wi-Fi?

**Comment by trupici** [comment]
Hi,

all follower gwatch data sources require permanent data connectivity. They
are getting data from related servers on the net (Dexcom share servers in
your case)

That's why I recommend local gwatch data sources. For Dexcom G6 use BYOD
(patched dexcom g6 app) or xdrip+ reading data directly from the sensor.

Juraj

Dňa st 6. 9. 2023, 10:42 jensni ***@***.***> napísal(a):

**Comment by jensni-ch** [comment]
It's working now, kind of. The g-watch app often looses connection to the watch5. We then have to restart the phone and the watch5 afterwards and then press "send all" in the g-watch app.

**Comment by trupici** [comment]
If the app looses connection then check if you have disabled battery optimization for gwatch (wear) app, galaxy wearable app, samsung accessory framework/library and also bluetooth app. When one of these apps is forced to sleep then the connection is broken.
To recover the connection try to use Force Sync menu option (or Reconnect (!) button in gwatch wear app) button in gwatch mobile app Packet view screen instead of restarting devices. This should be enough
