### ISSUE TITLE
No data on watch display

### ISSUE THREAD

**Issue by CrysAM1982** [trupici/G-Watch-Wear#3]
I'm having some issues getting my blood sugar to display on my watch.  I have a Samsung phone with the G Watch Wear app installed on it, and a Galaxy 5 watch with the G Watch watch face installed. I wear a Libre 3 and have my LibreLinkUp account set up. I'm not able to see any BG data on my watch face, but the G Watch widget on my phone is able to display my BG data. I attached photos. Thanks.

![Screenshot_20230322_172941_G-Watch Wear App](https://user-images.githubusercontent.com/128646186/227044673-81b355a1-f511-459d-98a0-b51eb52f53f3.jpg)

![Screenshot_20230322_172909_One UI Home](https://user-images.githubusercontent.com/128646186/227044707-4a5d5982-dcc1-4b1d-aed4-fc85412d5789.jpg)

![20230322_173009](https://user-images.githubusercontent.com/128646186/227044733-0af5e9ec-d093-4550-a169-b7e8df36402a.jpg)

**Comment by trupici** [comment]
Hi,

The mobile gwatch app doesn't see the gwatch watch face app...

Have you ever seen any readings on the watch?

I would try the following:
- Check the battery optimization settings for gwatch app, galaxy wearable
app, samsung accessory service and bluetooth. Disable it for all mentioned
apps, otherwise they can be put in forced sleep and the communication can
be broken.
- Open the Samsung Galaxy Wearable app and check if the watch is connected
with the app. Reconnect if possible.
- Then in gwatch Packet view press the 'Reconnect' button one or more times
and wait for the next reading.
- Also you can try to switch to another watch face for a moment and back.
This will restart the watch face app and can solve the problem. Wait for
the next reading after the gwatch watch face is restored.

If the issue occurred after the watch battery was shut off due to an empty
battery then you will need to reinstall the app (with the GW4 it was
sometimes necessary to reset the watch and reinstall). The newest solutions
to this issue can be found in G-Watch App Users group on facebook.

Juraj

**Comment by CrysAM1982** [comment]
Thank you so much, battery optimization was on for the Samsung Wearable app. It's working perfectly now!
