### ISSUE TITLE
Configurable snooze times for glucose alerts

### ISSUE THREAD

**Issue by davidmtml** [trupici/G-Watch-Wear#8]
Currently there is no way to change the snooze time on alerts.  The major issue with this is that often, especially at night, instances of hyperglycemia can be very long lasting.  Even if I take plenty of insulin, hyperglycemia episodes can last hours before they come back into range.  Being woken up every 15 minutes by my watch is not conducive to good sleep, and is really not helpful.  If my sugar was high 15 minutes ago...it's probably still high. A few things below that would be helpful.

1.  Allow changing the length of the snooze time. 
2. If that's not possible, changing the default length to 30 minutes or even 1 hour I feel would be more helpful.
3. Another option would be that if glucose is trending in the right direction (that is, currently in hyperglycemia but dropping), to not re-trigger the alert.

Thank you for your consideration!

**Comment by nigzak** [comment]
this would be very good to improve this ... I even start disconnecting bluetooth or remove watch if this happens because for me it is only annoy if this happen and I am longer on a "bad" level on the edge ... I even tried both buttons on alert screen and for me they are working "similar" ... if I still "high" the alert is triggered until you are down (did not find something in the wiki which explains the difference - but nevertheless, for me it is always "re-triggering")

An option could also be to have (probably it is like this?) to
X = do not trigger SAME alert again
SNOOZE = trigger SAME alert again in <configureable> time
SAME alert would be as example:
if HIGH => remember that HIGH alert was triggered last time and if "X" is used dont trigger again until another range like LOW, NORMAL or else is reached.

If I understand correct you have 
VERY HIGH
HIGH
NORMAL
LOW
VERY LOW

so you could split the section somehow into this and save where the "last" alert was active. If you change the section (ex: HIGH=>VERY HIGH) it can be checked if a alert must be (re-)triggered, a change into direction to "normal" is a "CAN TRIGGER", a change into the other direction to getting worse should be a "MUST TRIGGER"

```

High level:

if you were in some "alert" area and you stay in this area you have
a) snoozed => show alert in SAME area not before xx minutes
b) "x"'ed => show alert in SAME area not again

if you were in some "alert" area and change into "another alert" area oyu have
a) new area is "normal" => disable/reset all alerts
b) snoozed => show alert, ignore snooze because area changed
c) "x"'ed => show alert, ignore snooze because area changed

This would also fullfill as example "HIGH" => "LOW" or else


longer example to explain it better with examples:


// no alert before
BZ_SECTION=NORMAL

// reach HIGH
// BZ_SECTION=NORMAL (previous)
// SECTION_ACTUAL=HIGH
// => it is a change which is not getting "better" in direction of "normal"

Save "BZ_SECTION=HIGH"
VAR a) Show alert => user press "snooze" 15m 
VAR b) Show alert => user press "x" button to dissmiss

// after 15m still in HIGH
// BZ_SECTION=HIGH (previous)
// SECTION_ACTUAL=HIGH
// => no change, still high

Previous VAR a) => 15m expired   => again show alert
Previous VAR b) => don't show alert again ("ignore it")

// after xx m reaching VERY HIGH
// BZ_SECTION=HIGH (previous)
// SECTION_ACTUAL=VERY_HIGH
// => it is a change which is not getting "better" in direction of "normal"


Save "BZ_SECTION=VERY_HIGH"
Because Section got WORSE the old configurations are ignored, does not mind if snoozed or "x"'ed
VAR a) Show alert => user press "snooze" 15m 
VAR b) Show alert => user press "x" button to dissmiss

// after xx m reaching HIGH
// BZ_SECTION=VERY_HIGH (previous)
// SECTION_ACTUAL=HIGH
// => it is changing in direction of normal

Save "BZ_SECTION=HIGH"
Previous VAR a) => if 15m expired   => show alert
Previous VAR b) => don't show alert again ("ignore it"); reason: user know he is high and it gets better, still same alert is to hide

// after xx m reaching NORMAL
// BZ_SECTION=HIGH (previous)
// SECTION_ACTUAL=NORMAL
=> no alert required, normal should reset all alert things (snooze timers/...)
Save "BZ_SECTION=NORMAL"


// HINT EDGE CASES MUST BE CHECKED
it could happen that a user is on the edge and a alert is triggered very fast. For this case it smells that the alert should have a functionality to avoid this happens

example: NORMAL would be 70-100
10:00 => 100
10:02 => 101
10:03 => 100
10:04 => 102

if you follow the upper described approach you would trigger an aloert on 10:02 and one on 10:04
So it seems on the edge cases there is a special handling required to avoid annoying the user with it.
Therefore it seems some more thinking must be done because this can be very bad.

If you find a solution for it, it can be also have bad impacts.
Pro:
- you would hide the 10:04 alert && not show any other alert again because in the middle it was "normal"
Con:
- you won't show ANY alert again if you stay in HIGH after 10:04 - even if the user used "snooze"


Other possibility:
if you are on the edge save the NEW STATE different if it is close around the area of "NORMAL", example:
HIGH = 101 ...
NORMAL = 70...100
LOW = 69...
OFFSET = 5

10:00 => 100  => NO ALERT
10:02 => 101  => TRIGGER ALERT
10:03 => 100  => with knowing coming from HIGH add the offset (100+5 = STILL HIGH) to it for saving NEW BZ_SECTION and save it still as HIGH and NOT as normal, NO ALERT, DO NOT RESET TIMERS IF SNOOZED
10:04 => 102   => STILL in high, 10:03 saved as HIGH => NO ALERT
... TRIGGER ALERT => If still in high alert can be re-shown

I think it is not very easy to find a working version where you have a solution which satisfy all users ...
Probably there are also much more easier possibilities - that are only things which came to my mind on midnight writing ;)

```

If the original creator of this ticket had something else in mind than I am sorry and I can also create a ticket by myself to avoid putting different things into one ticket

**Comment by trupici** [comment]
The G-Watch Wear App is still in beta stage, once there will be a version 1.x then the alarm options will be updated as it was in classic gwatch app, including configurable sleep timer options
